### ISSUE TITLE
USB and display brightness not working

### ISSUE THREAD

**Issue by byrnes** [MirkoCovizzi/thinkpad-p51-hackintosh#1]
I applied your DSDT and SSDT patches, and they still don't work. Your SSDTs aren't being applied at all, though, because they haven't been added into sortedorder in the config.plist. After adding them, USB and brightness still don't work.

**Comment by MirkoCovizzi** [comment]
Try now. I fixed a mistype in the SSDT-2 patch. BTW, if you installed correctly as per the base guide https://www.tonymacx86.com/threads/guide-booting-the-os-x-installer-on-laptops-with-clover.148093/ USB should work, but only in a base form. The complete correct way will come soon since I don't have any USB 3.1 device nor any USB C device to properly make a SSDT patch for USB injection. Also, if you followed correctly the guide linked above, you wouldn't need any SortedOrder in the config.plist.
Another thing missing, but I will add it in the near future, is the correct BIOS config, which I will write in the README, otherwise the patches MAY not work (but should anyway, since they are in fact only patches and not compiled .aml).

On an unrelated note, I've seen that you have worked on a TpFancontrol fork for dual fan support. Would you be interested in working together to port the functionality over to OSX (without GUI of course)? The alternative would be to try to port thinkfan or other similar GNU/Linux tools.

**Comment by byrnes** [comment]
I did install via the base guide, and USB works when booting my config.plist, so I don't know why it doesn't work when booting yours. I'll dig around and see if I can fix it. I just tried your latest patch, and this is the error that it gives now: `715, 6088, Object is not accessible from this scope (_OFF)` and `2038, 3115, Not all control paths return a value (PDUB)`. I had no luck patching the dGPU out either. 

Once I get everything working, I was planning on porting some sort of fan control over. Seems to me like a Linux based utility may be easier to port, but I haven't looked into how macOS interfaces with things like fans.

**Comment by MirkoCovizzi** [comment]
For now don't use my config.plist, just use it as a reference (the only important thing added is the backlight patch). For what concerns the patches, you should tell me the process you followed, i.e. which patch you applied to which .dst. Also, patching is hardware dependent (even a difference in RAM, for example 1x16 vs 2x8 could make a difference) and BIOS config dependent, so you should give a complete list of both, then we'll see what to do. If your configuration is the same as mine you would only need to change BIOS settings.

**Comment by byrnes** [comment]
Seems like the issue with USB was due to USBinjectall.kext being quite out of date. Updating it fixes any issues with USB I had.

**Comment by MirkoCovizzi** [comment]
As a good measure update all the kexts you have. For what concerns brightness, instead, by following this guide https://www.tonymacx86.com/threads/guide-laptop-backlight-control-using-applebacklightinjector-kext.218222/ you should be able to make it work, even without my patch. The patch I wrote simply maps the keyboard brightness keys to the brightness increase/decrease, but the brightness functionality can be achieved already by following that simple guide (copy some files in the correct places and copy a kext patch on config.plist, refresh kextcache and you are good to go).

**Comment by byrnes** [comment]
I got brightness working myself, but for some strange reason there's no displays option in keyboard shortcuts so I can't assign any keys to turn brightness up or down.

**Comment by MirkoCovizzi** [comment]
To do that you need to use the patch "DSDT_brightness_keys_patch.txt" on the DSDT, then the display buttons will work properly and natively without messing with any keyboard options/shortcuts.

**Comment by MirkoCovizzi** [comment]
Can you tell me if the patches are working for you now? Thanks.
