### ISSUE TITLE
Thinkpad Ultra Dock USB unusable

### ISSUE THREAD

**Issue by the3asic** [MirkoCovizzi/thinkpad-p51-hackintosh#2]
Thanks for the effort first!
I happened to have an 170W Ultra Dock, but the USB port on it powers the USB devices just fine, but macOS can't recognize the devices.
Is there any workaround for this? Thx!

**Comment by MirkoCovizzi** [comment]
Did you use the SSDT-UIAC and SSDT-USBX? Also, if by devices you mean monitors, there is a high chance that external monitors won't work (I don't have a dock to try) since it appears that HDMI, DP and USB-C to VGA/HDMI all are connected to Nvidia which is disabled. If you already used both SSDTs, then it means you have to include the dock port to SSDT-UIAC since I only included the regular ports (4 usb 3.0) and the needed internal devices (Wifi module and camera). To do that you have to follow this guide https://www.tonymacx86.com/threads/guide-creating-a-custom-ssdt-for-usbinjectall-kext.211311/ and discover which logical port is mapped to the dock physical port, then add that to the SSDT-UIAC.

**Comment by the3asic** [comment]
Thanks for the detailed reply, I'll definitely have a try on this :)

**Comment by the3asic** [comment]
I've successfully enabled the Thinkpad Dock, and the port of the dock is HS04 & SS04 for the USB ports.
[SSDT-UIAC aml dsl.zip](https://github.com/MirkoCovizzi/thinkpad-p51-hackintosh/files/2151725/SSDT-UIAC.aml.dsl.zip)
The file above is the modified dsl and compiled aml file. Hope it could help someone :)
