### ISSUE TITLE
Installation fails with KP in phase 2

### ISSUE THREAD

**Issue by hanzoh** [MirkoCovizzi/thinkpad-p51-hackintosh#3]
I have tried installing 10.13.6 on a P51 (though without the 4K display, rest is the same as yours),
but it always fails when booting into phase 2 of the installation (the black screen with Apple logo, progress bar and time estimate).
Unfortunately, I cannot see the KP as the GUI part has already started (so -v and debug=0x100 do not help).

Do you have any idea or have you encountered the same?
I'm using Rehabman's config.plist for KBL and HD630, added your SSDT fix for the USB ports, and disabled the Nvidia card via SSDT.

**Comment by MirkoCovizzi** [comment]
To solve the issue you have to thoroughly read, understand and apply Rehabman's guide. Following the guide you are guaranteed 100% to have a correctly booting P51. The guide applies to any laptop and works universally on any laptop the same way. After that you can take the stuff you want from this repository to fix the features that don't work on a base hackintosh installation, but first you need to have a base hackintosh installation booting correctly. Since this issue is not related to this repository, I need to close it.
