### ISSUE TITLE
Have you tried installing NVIDIA Web Drivers?

### ISSUE THREAD

**Issue by lucaschen** [MirkoCovizzi/thinkpad-p51-hackintosh#8]
I have a ThinkPad P72, and I have tried installing High Sierra on it with discrete graphics. However, after installing the NVIDIA Web Drivers and changing boot settings to `nvda_drv=1 -v` (no `nv_disable=1`), I find that I am stuck in the boot screen, with no apparent error in the console.

On a separate issue, I have also tried installing Mojave with the NVIDIA card disabled, and I was able to achieve full graphics acceleration (QE/CI) and it was working fine. However, I could not connect external monitors to my display. Have you tried connecting external monitors to your hackintosh yet?

Thank you for your time.

**Comment by MirkoCovizzi** [comment]
Hi! I have not tried to install NVIDIA Web Drivers on High Sierra. The problem you are describing that happens at boot time is probably caused by a race condition between discrete and integrated GPUs. The only solution would be to disable discrete GPU, however, I think it's possible to make an ACPI patch that through ACPIpoller, after pressing a certain keyboard key (for example), enables the dedicated GPU again. I theorize that this wouldn't cause race conditions but I don't know how the drivers would react. At the moment I can't test though. For your second question, the hardware configuration of the P series is such that all external video ports are connected exclusively to the discrete GPU (you can verify this on Windows). Since the dedicated GPU is commonly disabled before boot, this leads to no output on external monitors. Not disabling the discrete GPU also doesn't seem to enable external output, even through USB type C (I've personally tested this), probably because of lack of proper Web Drivers support.

**Comment by lucaschen** [comment]
Yeah... I don't think NVIDIA Web Drivers works for my Quadro P600. I've received responses on other forums saying that no laptop GPUs are supported by the drivers, which seems to be true at least in my case. I can boot in discrete graphics mode from the BIOS (no internal GPU I presume), and I still cannot load the OS with nvda_drv=1 and NVIDIA Web Drivers installed.

Thank you for your response!
